### ISSUE TITLE
Dynamic route prefixes

### ISSUE THREAD

**Issue by ju5t** [laravel/octane#113]
- Octane Version: 0.1.0
- Laravel Version: 8.36.0
- PHP Version: 8.0.3 
- Database Driver & Version: Road Runner

### Description:

Sorry, this is more a question to clear things up than a bug, but I guess it might help others. It's also an attempt to fix another open source project. I am using https://github.com/mcamara/laravel-localization for our localisation. I am not a maintainer or contributor to that project, but it's pretty popular so I would like to help fix it.

Every translated route I visit in the browser results in a 404. I am pretty sure this needs to be fixed in `mcamara/laravel-localization`, but I need some help/guidance on how to do this. As not everyone will be familiar with this package, I will explain below.

The package uses a method to load the language prefix in the RouteServiceProvider.  The prefix of all routes is loaded with:

```php
Route::prefix(LaravelLocalization::setLocale())
```

The `setLocale` function will try to fetch the language from the url. If it doesn't exist, it returns null.

Language prefixes are: `en-us`, `nl-be`, as shown in the urls below:

- en-us/dashboard
- nl-be/dashboard

I assume the route prefix will be cached, as it is preloaded during initialisation, right? In that case, when it initially loads, the value will be null, as `setLocale()` won't have a request to parse (so far, all assumptions). That would explain why our translated pages don't work :)

I hope some of you can share some thoughts on what to do.

### Steps To Reproduce:

Install mcamara/laravel-localization in a fresh Laravel installation. That's pretty much it.

Thanks for all of the amazing work on Octane by the way. Awesome job!

**Comment by olssonm** [comment]
Yeah, that's an interesting case that probably a few will encounter. Haven't looked into mcamara/laravel-localization specifically if there is a way to build it to work differently.

But, you should be able to manually "preload" the localized routes to enable them with Octane, so instead of:

```php
Route::group(['prefix' => LaravelLocalization::setLocale()], function() {
    Route::get('/', ['uses' => 'SiteController@index'])->name('site.index');
    // All other localized routes
});
```

You could write:

```php
foreach (LaravelLocalization::getSupportedLocales() as $key => $locale) {
    Route::group(['prefix' => $key], function() {
        Route::get('/', ['uses' => 'SiteController@index'])->name('site.index');
        // All other localized routes
    });
}
```

Running `php artisan route:list` should now display all available localized routes. Note that if the `localeSessionRedirect` and `localizationRedirect`-middlewares are used you might encounter other redirect-issues.

**Comment by ju5t** [comment]
@olssonm cheers, sometimes a fresh pair of eyes helps :) 

This works for me!

**Comment by ju5t** [comment]
You're asking me? I don't know! :)

I would think this needs to be fixed in Octane. As what used to be ok, all of the sudden doesn't work anymore. But there might be reasons for not supporting this too.

If I knew where to start and thought it was 100% Octane, I would have definitely PR'd it.

I will leave it as is for now. Thanks for the follow up though!

**Comment by mcolominas** [comment]
Laravel octane has no problem with this, when using laravel octane, you have to think differently from what you normally program, in the case of routes, whether they are cached or not, they only run once and stay loaded, for Therefore, when you visit for the first, second, third or more times, you will only get the routes that are already loaded, therefore, laravel octane, offers you ways to restart things in each cycle, through listeners, therefore If you have dynamic routes that change with each request, you have to restart it manually, as I have given you in the example of https://github.com/mcamara/laravel-localization/issues/780#issuecomment-981962203

**Comment by ju5t** [comment]
@mcolominas thanks for the suggestion, it's looks like a good solution. But it's probably not for us.

I know how Octane works, but we no longer use mcamara/laravel-localization. We've switched to a custom solution for localisation and also dropped the idea of using Octane for now. We don't have a real incentive for it at the moment (speed, cost, or something else) and as you said, it comes with some caveats.

**Comment by mcolominas** [comment]
@ju5t  I'm sorry to hear that, but I understand, since it's been several months and no one responded.

I also have my own (private) packet for translating urls, since I don't like mcamara/laravel-localization, and it lacks some functions that my package has.

Regarding the performance of laravel octane, I can say that you can see a noticeable difference, in terms of speed, in a basic installation, it is usually 40-50% faster than normal laravel (at least on my server and using swole), in terms of cost, having the resources loaded, it usually processes less things, in addition to that it can receive more requests per second (https://moduscreate.com/blog/boost-your-laravel-project-performance-with-octane/), for projects that it is calculated that it will receive many requests per second, I would recommend using the laravel octane .

Also, in my opinion, I would only recommend using laravel octane for new projects, since as I said before, it could break normal projects

**Comment by tashuo** [comment]
> [@olssonm](https://github.com/olssonm) cheers, sometimes a fresh pair of eyes helps :)
> 
> This works for me! Not sure if it's the perfect solution but I'll leave that to other people.
> 
> edit: unfortunately there are still some issues, but that's probably not part of this issue. The translations aren't getting through as expected so I have to look into that.

maybe you missed the `LaravelLocalization::setLocale()`
