### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by caiking** [laravel/octane#171]
- Octane Version:0.1.0
- Laravel Version: 8.36.2
- PHP Version: 8.0.3
- Server: Swoole-4.6.5

### Description:

i just install laravel,swoole,octane

and start with "php artisan octane:start --port=13000 --watch"

add code like this:

```
<?php


namespace App\Http\Controllers;


class TestController extends Controller
{
    public function index()
    {
        return memory_get_usage()/1024/1204;
    }
}
```

and this:

`Route::get('/test', App\Http\Controllers\TestController::class."@index");`

then did nothing

and i requested "http://127.0.0.1:13000/api/test" in chrome ，often and often

i got these respopnse:
13.533650851329
13.710976432724
13.747858700166 
 ...
 15.084081706811
 ...

The numbers are not going down

**Comment by Namoshek** [comment]
Try configuring a lower threshold for garbage collection in `config/octane.php`.

**Comment by albertcht** [comment]
Sometimes it's difficult to track memory leak in your Laravel project in long-running environment. In traditional PHP lifecycle, developers don't need to worry about it because all the resources will be destroyed after each request.

There might be somewhere using global variable wrongly in your project (maybe in other packages). You can try to add `max-requests` argument when you start the server. And workers will be gracefully restarted after serving that amount of requests to avoid memory leaks.

```
php artisan octane:start --max-requests=250
```

**Comment by themsaid** [comment]
Investigating this. Thanks for reporting.

**Comment by linaspasv** [comment]
I have experienced the same on a fresh laravel install.

**Comment by themsaid** [comment]
fixed here https://github.com/laravel/octane/pull/181

**Comment by kocoten1992** [comment]
Hi @themsaid, how you was able detect memory leak?

I got a leak and was trying to find a memory leak detector for swoole, but find none so far.
