### ISSUE TITLE
NGINX recommended setup

### ISSUE THREAD

**Issue by elfeffe** [laravel/octane#254]
I think NGINX is required, to handle SSL.
Maybe we need a recommended conf for the web server

**Comment by nunomaduro** [comment]
No plans on adding a recommended NGINX setup.

**Comment by microerror** [comment]
> No plans on adding a recommended NGINX setup.

Do you suggest to turn to other solutions that do mention how to handle SSL termination and clean the stack between requests in that case?

**Comment by n3m3s7s** [comment]
> > No plans on adding a recommended NGINX setup.
> 
> Do you suggest to turn to other solutions that do mention how to handle SSL termination and clean the stack between requests in that case?

Well, I did not tried it, but I think that if You want to use Nginx is quite easy.
Octane is like a "daemon" listening on a TCP port, that can be any available port (not standard 80 or 443 if You are using Nginx or a webserver in general).

I think that is quite similar when you define an upstream (in Nginx) with Node or Python or Golang or every language capable of creating a server/daemon on TCP that can handle HTTP requests and return HTTP responses.

In that case You can also span multiple Octane services listening on different TCP ports, and then use a very simple load-balancing in Nginx (if You want a "real" load-balancer You should use something else).

The advantage is that every single Octane instance does not require to handle SSL, since the certificate is handled by Nginx instead, which "proxies" the request to the underline upstream.

For example: let's say that we span 2 Octane instances with Swoole on IP 127.0.0.1 and ports 61337,61338.

then - a very simple - Nginx config may look like this:

` http {    
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    gzip on;
    gzip_comp_level 6;
    gzip_vary on;
    gzip_min_length  1000;
    gzip_proxied any;
    gzip_types text/plain text/html text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_buffers 16 8k;
 
    ssl_certificate /some/location/sillyfakesociety.com.bundle.crt;
    ssl_certificate_key /some/location/sillyfakesociety.com.key;
    ssl_protocols        SSLv3 TLSv1;
    ssl_ciphers HIGH:!aNULL:!MD5;

    upstream octane_upstream {
      ip_hash; # session persistance
      server 127.0.0.1:61337;
      server 127.0.0.1:61338;
      keepalive 64;
    }

    # Redirect non-www to www
    server {
      listen 80;
      listen 443 ssl;

      server_name sillyfakesociety.com;
      return 301 $scheme://www.sillyfakesociety.com$request_uri;
    }

    server {
        listen 80;
        listen 443 ssl;

        server_name www.sillyfakesociety.com;

        # Handle static assets, but is up to You
        location ~ ^/(images/|img/|javascript/|js/|css/|stylesheets/|flash/|media/|static/|robots.txt|humans.txt|favicon.ico) {
          root /usr/local/silly_fake_society/laravel/public/assets;
          access_log off;
          expires max;
        }

        location / {
          proxy_redirect off;
          proxy_set_header   X-Real-IP            $remote_addr;
          proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;
          proxy_set_header   Host                   $http_host;
          proxy_set_header   X-NginX-Proxy    true;
          proxy_set_header   Connection "";
          proxy_http_version 1.1;
          proxy_pass         http://octane_upstream;
        }
    }
}`

PLEASE NOTE that is just an example, nothing official and do not copy/paste without understanding what is does and without customizing to your application's needs.
Bye

**Comment by n3m3s7s** [comment]
> I don't understand if the plan is to use Octane directly as a server. Swoole can handle SSL, but in my point of view NGINX is much more reliable.
> I don't know if it will be slower using a web server in the middle.
> Laravel offers a recommended NGINX config, I don't understand why Nuno's answer was that short.

IMHO it really depends on your application: for example I have used Octane to develop a microservice which is basically an API server that receives requests only on local network and does not host any static asset such as JS/CSS/etc.;

In this scenario - but, again, this is just my opinion - Octane is a perfect-fit because I do not need SSL or a web-server in general and everything is faster because there is no "proxy/cgi" or another service that sit in front of Laravel.

However, If you have a Nginx instance even in front of Octane I do not think that it will be slower: Nginx is quite lightweight and it does its job very well. 

I've used Nginx in production for almost seven year and is perfect with Laravel, serving Node.js upstream and - If you like at my previous comment - it should not be a problem using Octane within Nginx, but I do understand that is not a typical scenario for Octane and its developers.

Furthermore even if in the Laravel documentation there is a small Nginx config I doubt that can de used in production as it is, and so for Octane or every service You deploy in production.
Bye!

**Comment by Radiergummi** [comment]
> I don't understand if the plan is to use Octane directly as a server. Swoole can handle SSL, but in my point of view NGINX is much more reliable.
> I don't know if it will be slower using a web server in the middle.
> Laravel offers a recommended NGINX config, I don't understand why Nuno's answer was that short.

To chime in here, don't worry about nginx slowing you down: It's a rock-solid, extremely fast web server that comes with almost no latency overhead. What's much more important is all nginx does for you automatically by handling the HTTP protocol intricacies, load balancing, logging and thousands of other things before a request even reaches your application. Whatever you do, do yourself a favor and _do not_ expose your application server to the web directly, but place it behind a reverse proxy such as nginx.

**Comment by francoism90** [comment]
Sorry for the bump, but I'm experimenting with http3/quic on nginx:

```bash
Internal Server Error
```

It does work fine with `curl -k http://localhost:3000`, but it doesn't work when doing a proxy.

I don't think `swoole` should use https, but even when I do, I'm getting the same error.
