### ISSUE TITLE
Swoole table as a  queue / session driver method ?

### ISSUE THREAD

**Issue by nicolasvac** [laravel/octane#273]
As said in the title, for session driver method currently there are:

Supported: "file", "cookie", "database", "apc",
    |            "memcached", "redis", "dynamodb", "array"

In case octane and swoole are used, it should be a nice touch to have swoole tables as a driver method.

 Same goes for queue

Thanks.

**Comment by themsaid** [comment]
You'll lose all session data when the swoole server restarts.

Also why would you use Octane workers for queues?

**Comment by sikhlana** [comment]
There is a limit to how much data swoole tables can handle. What about the scenarios where there are more pending jobs / active sessions than you specified or more payload than you expected? From what I've seen, you cannot dynamically change the table size.

### If I am not mistaken:

Swoole does support shared memory, but that's only between the workers spawned by the *master* process. So you have to implement running dispatched jobs within these workers which might hinder the actual usage of the package: "serving HTTP requests at supersonic speeds" when there are long-running jobs and no available worker.

And since the tables can't be accessed out of the "swoole sandbox", `php artisan queue:work` wont work.

**Comment by nicolasvac** [comment]
For local deployments or test server, it can be "time wasting" to setup a redis server just for queues and cache, it's something a swoole table would do just fine. 

Runs out of memory ? Fine, redis does the same, stops accepting new data once the memory is full.
Loosing data when the server restarts ? Fine, redis does loes all the data once restarted. While is true it's a lot more common to restart the octane server than redis, at least for cached values this is fine.

**Comment by themsaid** [comment]
You can use database for queues and caching. You don't even need to run Octane locally.
