### ISSUE TITLE
[Question]: Octane Server Use More Memory

### ISSUE THREAD

**Issue by myckhel** [laravel/octane#283]
- Octane Version: 1.0.0
- Laravel Version: 8.41.0
- PHP Version: 8.0.6
- Server & Version: Swoole
- Database Driver & Version: mysql

### Description:
Octane Server used more memory
![Screenshot 2021-05-18 at 13 22 48](https://user-images.githubusercontent.com/34090541/118650645-9a0a8180-b7dc-11eb-9e06-52bbeac04ccd.png)

Than Default server

![Screenshot 2021-05-18 at 13 23 54](https://user-images.githubusercontent.com/34090541/118650390-4ef06e80-b7dc-11eb-9b2e-db5b2acbe692.png)

Is this a normal behaviour?

**Comment by sikhlana** [comment]
Off topic: What are you using for this stat?

**Comment by myckhel** [comment]
> Off topic: What are you using for this stat?

https://github.com/laravel/telescope

**Comment by sikhlana** [comment]
Looks like Telescope uses `memory_get_peak_usage()` for retrieving the memory usage. One scenario that can happen is the memory usage peaked for some other (previous) request which didn't get a reset since the process is long running unlike `php-fpm` or similar which kills the process after every request, resetting the peak usage.

This is just my opinion, I might be wrong though.

**Comment by nunomaduro** [comment]
@sikhlana is correct.
