### ISSUE TITLE
Cache remember method returns null

### ISSUE THREAD

**Issue by dorinniscu** [laravel/octane#348]
- Octane Version: 1.0.8
- Laravel Version: 8.50.0
- PHP Version: 8.0
- Server & Version: Swoole 4.6.7
- Database Driver & Version: MySQL 8.0.25

Everything works as expected when using the redis store for example.

`cache()->store('redis')->remember("redis_key", now()->addMinutes(), fn() => 'redis_value');`

Cache::remember() method does not stores the value when using Laravel Octane Cache. (returns null)

`cache()->store('octane')->remember("octane_key", now()->addMinutes(), fn() => 'octane_value');`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by dorinniscu** [comment]
@driesvints  I tested it again and seems that the octane driver is not persistent. If I use **put** then **get**  immediately will receive the value, if I use **put** then refresh the page the value will be null. This is only for **Octane driver**. **Redis** works fine.

```
cache()->store('octane')->put("test_key",  'test_value', now()->addMinutes() );

cache()->store('octane')->get("test_key"); => returns null
```

Redis works as expected.

```
cache()->store('redis')->put("test_key",  'test_value', now()->addMinutes() );

cache()->store('redis')->get("test_key"); => returns test_value
```

**Comment by corsair** [comment]
Hello there, I am also experiencing this issue while just using Octane under normal conditions and not specifying the cache to utilize Octane's cache.

When making changes to models, the cache is not persisting to all workers. An example of this is when deleting a model and then refreshing a page that displays all remaining models, every refresh will result in either the just deleted model still persisting, or it being already deleted. This has made it virtually pointless to utilize/implement Octane because of this issue.

If it matters, cache driver is set to "redis".

Octane Version: 1.0.11
Laravel Version: 8.60.0
PHP Version: 8.0.10 w/ OPcache 8.0.10
