### ISSUE TITLE
Why slow request with roadrunner

### ISSUE THREAD

**Issue by nhuantg-0950** [laravel/octane#471]
- Octane Version: "^1.2",
- Laravel Version: v8.80.0
- PHP Version: 8.1.1
- Server & Version: RoadRunner v2.7.4
- Database Driver & Version:
- OS: Mac m1

### Description:

i use laravel sail and autocannon to test benchmark:
`autocannon -c 100 -d 10 http://127.0.0.1/test`

route only return welcome page:
```
Route::get('/test', function () {
    // \Log::info('start:'.date('H:i:s.u'));
    $html= view('welcome');
    // \Log::info('end  :'.date('H:i:s.u'));

    return $html;
});
```
![image](https://user-images.githubusercontent.com/49549426/151850616-ee19ca4e-08d6-41bc-93d6-555d36fbec86.png)

**... and continue to increase until 14470.12 ms**

**Comment by nunomaduro** [comment]
This issue happens with a fresh Laravel project, or in your existing Laravel project?

**Comment by nhuantg-0950** [comment]
It happens with new project installed from `curl -s "https://laravel.build/example-app" | bash`

**Comment by nunomaduro** [comment]
I was not able to reproduce the issue in a fresh Laravel project, and the latest versions of PHP, Octane and Roadrunner. We are going to pay attention to see if someone else reports this issue, meanwhile you can try to understand in your side where this issue is coming from and why is only effecting your system.

**Comment by msonowal** [comment]
I think in case of sail this is reproduceable
