### ISSUE TITLE
Observers afterCommit attribute is ignored

### ISSUE THREAD

**Issue by L3o-pold** [laravel/octane#517]
- Octane Version: 1.2.8
- Laravel Version: 9.11.0
- PHP Version: 8.1.1
- Server & Version: RoadRunner 2.9.4 but also reproduced with Swoole
- Database Driver & Version: mysql/mysql-server:8.0

### Description:

Observers `afterCommit` attribute is ignored if set to true.

### Steps To Reproduce:

Using https://github.com/L3o-pold/bug-report

```shell
composer install
php artisan migrate
php artisan octane:start
```

Then go to http://127.0.0.1:8000 

In the `storage/logs/laravel.log` you will see:

```log
[2022-05-10 07:21:36] local.DEBUG: App\Observers\UserObserver::creating  
[2022-05-10 07:21:36] local.DEBUG: After saving the model  
[2022-05-10 07:21:36] local.DEBUG: After the transaction  
```

If you are running the same example without octane (`php artisan serve`) you will see that `afterCommit` is used correctly:

```log
[2022-05-10 07:22:11] local.DEBUG: After saving the model  
[2022-05-10 07:22:11] local.DEBUG: App\Observers\UserObserver::creating  
[2022-05-10 07:22:11] local.DEBUG: After the transaction  
```

**Comment by Namoshek** [comment]
After some debugging, I found a solution to the issue: adding `db.transactions` to the `warm` array in `config/octane.php`:
```php
/*
|--------------------------------------------------------------------------
| Warm / Flush Bindings
|--------------------------------------------------------------------------
|
| The bindings listed below will either be pre-warmed when a worker boots
| or they will be flushed before every new request. Flushing a binding
| will force the container to resolve that binding again when asked.
|
*/

'warm' => [
    ...Octane::defaultServicesToWarm(),
    'db.transactions',
]
```

The reason seems to be that the `User::$dispatcher` has its own `$container` which resolves a different `db.transactions` than `app()->make('db.transactions')`. While `app()->make('db.transactions')` has a transaction level > 0, the one resolved by the dispatcher does not, causing [immediate callback execution](https://github.com/laravel/framework/blob/89d500f0c8e3706d7cb87eecb616c59ad9e921ae/src/Illuminate/Database/DatabaseTransactionsManager.php#L96).

While this seems to work, I'm not sure whether it is a good idea to do this. Could it be that the setup calls in  [`DatabaseServiceProvider::boot()`](https://github.com/laravel/framework/blob/89d500f0c8e3706d7cb87eecb616c59ad9e921ae/src/Illuminate/Database/DatabaseServiceProvider.php#L27-L32) have something to do with this?

**Comment by driesvints** [comment]
Thanks @Namoshek, I've pinged @taylorotwell to have a look at this.
