### ISSUE TITLE
[bug] Frankenphp cannot return multiple cookie

### ISSUE THREAD

**Issue by aldinokemal** [laravel/octane#951]
### Octane Version

2.4

### Laravel Version

10

### PHP Version

8.2

### What server type are you using?

FrankenPHP

### Server Version

-

### Database Driver & Version

MySQL

### Description

Previousely I'm using laravel octane Swoole, this code is working fine

```php
Cookie::queue('authenticated', encrypt($jwt), $oneYear, '/', config('app.domain'), true, true);
Cookie::queue('access_token', $accessToken, $oneYear, '/', config('app.domain'), true, true);

return redirect($this->getRedirectCallbackURL() ?? config('app.frontend_url'));
```

However when I tried to migrate into FrankenPhp my code got error 502 gateway

<img width="876" alt="image" src="https://github.com/user-attachments/assets/573bd516-29a2-4499-a1d9-75f1fd80502b">

### Steps To Reproduce

Deploy in nginx then proxy pass to laravel octane, if I comment one of Cookie::queue, it will working

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
