### ISSUE TITLE
Serialization of 'Laravel\Octane\Tables\OpenSwooleTable' is not allowed

### ISSUE THREAD

**Issue by MatusBoa** [laravel/octane#954]
### Octane Version

2.5.5

### Laravel Version

11.23.5

### PHP Version

8.3.10

### What server type are you using?

Open Swoole

### Server Version

22.1.2

### Description

When I try to pass query builder to `Octane::concurrently` closure, serialization exception is thrown.

<img width="1369" alt="image" src="https://github.com/user-attachments/assets/b4187c59-7edb-42a7-8d2c-093cc2166c63">

### Steps To Reproduce

```php
$query = DB::table('products')->limit(10);

Octane::concurrently([
    static function () use ($query) {
        return $query->get();
    },
]);
```

**Comment by chojnicki** [comment]
I would like to confirm that it appears also on regular Swoole, so 

`Serialization of 'Laravel\Octane\Tables\SwooleTable' is not allowed {"exception":"[object] (Exception(code: 0): Serialization of 'Laravel\\Octane\\Tables\\SwooleTable' is not allowed at /var/www/html/vendor/laravel/serializable-closure/src/Serializers/Signed.php:68)`

Not sure if it's new bug or just limitation because it's first time when I need to pass builder.

**Comment by crynobone** [comment]
To use this feature, a class must implement a serializable interface. It seems that this is not supported at the moment. Best to just generate the query directly within the closure:

```php
Octane::concurrently([
    static function () use ($query) {
        return DB::table('products')->limit(10)->get();
    },
]);
```
